### ISSUE TITLE
어떻게 쓰는건가요?

### ISSUE THREAD

**Issue by item4** [yoo2001818/AheuiChem#2]
lexifdev님의 추천(?)을 받고 보니까 뭔가 굉장한 것 같은데 설치 및 사용법을 알려주세요

**Comment by yoo2001818** [comment]
Grunt로 빌드하셔서 사용하면 됩니다.

node.js 설치하시고 프로젝트 디렉토리에서

```
npm install
npm install grunt-cli -g
grunt
```

하면 `build/` 폴더에 완성된 파일들이 생기는데 지금 코드 입력받는건 구현이 안되서
`index.html`의 `pre#source`에 직접 코드를 넣고 돌리셔야해요 ㅠㅠ

README.md에 적어놔야겠네요
